from enum import StrEnum


class ErrorCode(StrEnum):
    PERMISSION_DENIED = "PERMISSION_DENIED"
    FIELD_REQUIRED = "FIELD_REQUIRED"
    GROUP_DOES_NOT_EXIST = "GROUP_DOES_NOT_EXIST"
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
    EMAIL_TAKEN = "EMAIL_TAKEN"
    INVALID_PASSWORD = "INVALID_PASSWORD"
    VALIDATION = "VALIDATION_ERROR"
    GROUP_EXISTS = "GROUP_EXISTS"
    PERMISSION_EXISTS = "PERMISSION_EXISTS"
    NOT_FOUND = "NOT_FOUND"
    FORBIDDEN = "FORBIDDEN"
    UNAUTHORIZED = "UNAUTHORIZED"
    CONFLICT = "CONFLICT"
    BAD_REQUEST = "BAD_REQUEST"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    PERMISSION_NOT_FOUND = "PERMISSION_NOT_FOUND"
