"""permission_remove_unique_constraint_from_name_field

Revision ID: a7da70788259
Revises: 4350370828e3
Create Date: 2025-10-26 20:57:53.162911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7da70788259'
down_revision: Union[str, Sequence[str], None] = '4350370828e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_permission_name'), 'user_permission', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_user_permission_name'), 'user_permission', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
