"""update convension

Revision ID: c95b0f4608b2
Revises: 3113ce80e428
Create Date: 2025-10-13 03:31:44.176678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c95b0f4608b2'
down_revision: Union[str, Sequence[str], None] = '3113ce80e428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_group_permission_code_name_key'), 'user_group_permission', type_='unique')
    op.drop_constraint(op.f('user_group_permission_name_key'), 'user_group_permission', type_='unique')
    op.create_unique_constraint(op.f('uq__user_group_permission__code_name'), 'user_group_permission', ['code_name'])
    op.create_unique_constraint(op.f('uq__user_group_permission__name'), 'user_group_permission', ['name'])
    op.drop_index(op.f('ix_user_group_permission_link_group_id'), table_name='user_group_permission_link')
    op.drop_index(op.f('ix_user_group_permission_link_permission_id'), table_name='user_group_permission_link')
    op.create_index(op.f('ix__user_group_permission_link__group_id'), 'user_group_permission_link', ['group_id'], unique=False)
    op.create_index(op.f('ix__user_group_permission_link__permission_id'), 'user_group_permission_link', ['permission_id'], unique=False)
    op.drop_constraint(op.f('user_groups_name_key'), 'user_groups', type_='unique')
    op.create_unique_constraint(op.f('uq__user_groups__name'), 'user_groups', ['name'])
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_index(op.f('ix_users_group_id'), table_name='users')
    op.drop_index(op.f('ix_users_middle_name'), table_name='users')
    op.drop_index(op.f('ix_users_surname'), table_name='users')
    op.create_index(op.f('ix__users__email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix__users__first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix__users__group_id'), 'users', ['group_id'], unique=False)
    op.create_index(op.f('ix__users__middle_name'), 'users', ['middle_name'], unique=False)
    op.create_index(op.f('ix__users__surname'), 'users', ['surname'], unique=False)
    op.create_unique_constraint(op.f('uq__users__email'), 'users', ['email'])
    op.drop_table_comment(
        'users',
        existing_comment='Пользователи системы',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'users',
        'Пользователи системы',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(op.f('uq__users__email'), 'users', type_='unique')
    op.drop_index(op.f('ix__users__surname'), table_name='users')
    op.drop_index(op.f('ix__users__middle_name'), table_name='users')
    op.drop_index(op.f('ix__users__group_id'), table_name='users')
    op.drop_index(op.f('ix__users__first_name'), table_name='users')
    op.drop_index(op.f('ix__users__email'), table_name='users')
    op.create_index(op.f('ix_users_surname'), 'users', ['surname'], unique=False)
    op.create_index(op.f('ix_users_middle_name'), 'users', ['middle_name'], unique=False)
    op.create_index(op.f('ix_users_group_id'), 'users', ['group_id'], unique=False)
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_constraint(op.f('uq__user_groups__name'), 'user_groups', type_='unique')
    op.create_unique_constraint(op.f('user_groups_name_key'), 'user_groups', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix__user_group_permission_link__permission_id'), table_name='user_group_permission_link')
    op.drop_index(op.f('ix__user_group_permission_link__group_id'), table_name='user_group_permission_link')
    op.create_index(op.f('ix_user_group_permission_link_permission_id'), 'user_group_permission_link', ['permission_id'], unique=False)
    op.create_index(op.f('ix_user_group_permission_link_group_id'), 'user_group_permission_link', ['group_id'], unique=False)
    op.drop_constraint(op.f('uq__user_group_permission__name'), 'user_group_permission', type_='unique')
    op.drop_constraint(op.f('uq__user_group_permission__code_name'), 'user_group_permission', type_='unique')
    op.create_unique_constraint(op.f('user_group_permission_name_key'), 'user_group_permission', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('user_group_permission_code_name_key'), 'user_group_permission', ['code_name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
